# Generated by Django 4.2.23 on 2025-07-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number_hash',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True),
        ),
    ]
